name: anaquel
description: "Sistema de gestión de lectura"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_popup: ^3.3.0
  flutter_svg: ^2.0.10+1
  forui: ^0.4.0
  forui_assets: ^0.2.0
  go_router: ^14.2.7
  scaled_app: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#941932"
  adaptive_icon_foreground: "assets/icon/logo-icon.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
