name: anaquel
description: "Sistema de gestión de lectura"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_notifications: ^0.10.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  easy_localization: ^3.0.7
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  forui: ^0.8.0
  forui_assets: ^0.8.0
  go_router: ^14.2.7
  image_picker: ^1.1.2
  introduction_screen: ^3.1.14
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  scaled_app: ^2.3.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#941932"
  adaptive_icon_foreground: "assets/icon/logo-icon.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icon/
    - assets/get_started/
    - assets/translations/
