[project]
name = "anaquel-api"
version = "0.1.0"
description = "Book and AI provider"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "uvicorn>=0.32.1",
]
